### ISSUE TITLE
Error while connecting to Cassandra ( storer) module

### ISSUE THREAD

**Issue by mitsaravanan** [47deg/twitter-sentiment#2]
Using the following Cassandra version
[cqlsh 5.0.1 | Cassandra 4.0.0.2284 | DSE 6.0.0 | CQL spec 3.4.5 | DSE protocol v2]

Tried to run the code in GCP. 
1) reader module works fine. Able to ingest messages into pubsub.
2) storer module fails with the following exception.
`
**[error] (run-main-0) com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host /localhost:9042: Host /localhost:9042 requires authentica
tion, but no authenticator found in Cluster configuration
[error] com.datastax.driver.core.exceptions.AuthenticationException: Authentication error on host /localhost:9042: Host /localhost:9042 requires authentication, but no 
authenticator found in Cluster configuration
[error]         at com.datastax.driver.core.AuthProvider$1.newAuthenticator(AuthProvider.java:40)**
`

3) There should be a provision to add username and password similar to the following 
`
**val conf = new SparkConf(true).set("spark.cassandra.connection.host", "localhost").set("spark.cassandra.auth.username", "cassandra").set("spark.cassandra.auth.password", "password")**
`

**Comment by mitsaravanan** [comment]
Followed all steps as per the blog 
**https://www.47deg.com/blog/pubsub-cassandra-docker/**
1) Created gcp account
2) Created pub-sub topic and subscription
3) Installed Cassandra cluster with opscenter 
4) Created twitter app and got teh credentials
4) Ran reader module
5) Ran storer module ( Failed with Cassandra connection error)

**Comment by vejeta** [comment]
Hi @mitsaravanan, I see you are using Datastax Cassandra instead of Apache Cassandra.
There is no problem in that, although the example explained how to use it with that installation that used no authentication.

I can have a look later to make it work with Cassandra with authentication.

In the meanwhile, you can modify https://github.com/47deg/twitter-sentiment/blob/master/storer/src/main/resources/application.conf to set up the authentication configuration, or use Apache Cassandra to see how the example works.

**Comment by mitsaravanan** [comment]
Thanks vejeta. I tried filling in the values  in the file [https://github.com/47deg/twitter-sentiment/blob/master/storer/src/main/resources/application.conf ](url) for the following values
  username = ""
  password = ""

Still it did not work.

I will try with apache cassandra and see how it goes.

**Comment by vejeta** [comment]
@mitsaravanan , you can modify the application.conf to provide the username and password for the configured Cassandra through the credential keys:

In this example, we use `cassandrauser` and  `cassandrapass`

e.g.:
```
cassandra {
  database = localhost
  twittersentiment.keyspace = twittersentiment
  twittersentiment.preparedStatementCacheSize = 100
  twittersentiment.session.contactPoint = 127.0.0.1
  twittersentiment.session.withPort = 9042
  twittersentiment.session.credentials.0 = "cassandrauser"
  twittersentiment.session.credentials.1 = "cassandrapass"
  twittersentiment.session.queryOptions.consistencyLevel = ONE
}
```

Remember, that besides showcasing how to work with Google PubSub with Scala, the article also featured the usage of integration tests with the same software being run in the docker instances than in production. This example used Apache Cassandra, although this might not be your concern, just take it into account, to also modify the integration tests accordingly if you want.

**Comment by vejeta** [comment]
To know more about how to work with Cassandra with [Quill](https://github.com/getquill):

See: https://github.com/getquill/quill/blob/master/README.md

**Comment by vejeta** [comment]
I think this comment resolved the question. Please, reopen if you need anything else.
